### ISSUE TITLE
🌟 Implement CUDA version of radius_pbc

### ISSUE THREAD

**Issue by blondegeek** [e3nn/e3nn#179]
**Is your feature request related to a problem? Please describe.**
Many folks use periodic boundary conditions for constructing graphs of e.g. crystals and molecular dynamics unit cells. We'd like to have this implemented in `torch_cluster` (which we depend on) and we'd like for it to be fast.

**Describe the solution you'd like**
We'd like a CUDA version of Mario's code here:
https://github.com/mariogeiger/pytorch_cluster/blob/radius_graph_pbc/torch_cluster/radius_pbc.py

**Comment by Linux-cpp-lisp** [comment]
This is not as simple as one would hope — it's very easy to write a wrong periodic neighbor list. I've seen a few CUDA implementations of neighbor lists, but all seem to be complex and quite closely entangled with whatever software they're part of. Simplest solution I've thought of so far would be to adapt the [`ase` neighborlist](https://gitlab.com/ase/ase/-/blob/master/ase/neighborlist.py) by replacing `numpy` calls with `torch` calls and then compiling with TorchScript to run on GPU. 

Because of licensing (`ase` is LGPL) that would have to be a standalone LGPL utility library, not part of `torch_geometric` (MIT license), though.

**Comment by Linux-cpp-lisp** [comment]
Actually a better option might be [`cupy`](https://cupy.dev/), which can act as a drop-in replacement for numpy and interoperates with torch Tensors.

**Comment by mariogeiger** [comment]
Looks like `cupy` improved a lot. Would you use the custom kernel feature of `cupy`?

**Comment by Linux-cpp-lisp** [comment]
You could — I was thinking more of find/replace `np` -> `cp` and using the ASE code. (Similarly I think you could do the same for TorchScript with `np` -> `torch` and some simple fixes like `shape` -> `size`.) I'm wary about writing neighborlist code from scratch; I've had some bad experiences with generic triclinic periodic neighborlists breaking in unexpected ways when not written very carefully and don't really feel like taking the time to do that unless I have a very good reason to.

**Comment by mariogeiger** [comment]
I would favor `pytorch` then because it works on both cpu and gpu

**Comment by bdice** [comment]
I'm decently familiar with this area and agree that this is a hard problem, frequently resulting in buggy code if not handled with extreme care (there are many non-trivial edge cases). I concur with @Linux-cpp-lisp about _not_ writing from scratch. I've been a part of several conversations with authors of molecular dynamics engines / analysis packages about trying to extract the neighbor finding code from permissively licensed packages in a way that supports CPU/GPU; C++/Python, but nothing of the sort exists to my knowledge.

There are also a separate set of challenges if users decide they want to use a number of nearest neighbors (like k-NN) instead of a radius cutoff. The optimal algorithms are not quite the same for that case. Almost all approaches require sophisticated spatial data structures, and the best choice of spatial data structure will depend on the distribution of the points inside the periodic box (homogeneous density can favor cell lists, while a dense blob of particles in the center can be better with a tree-based method -- but the implementation details can make one approach faster than the other in practice).

The closest things I know of:
- https://github.com/mphowardlab/neighbor/ is used internally for HOOMD-blue, it's header-only and GPU-focused. The part that handles periodic boxes is in HOOMD-blue's code base.
- freud (disclaimer, I maintain the package) has fast, C++ CPU-only implementations using Intel TBB for parallelism. The algorithms are based on those in HOOMD, with some extensions. https://github.com/glotzerlab/freud/tree/master/cpp/locality There are Cython bindings that could be used by external packages.

Many difficult corner cases can be found in the freud unit tests: https://github.com/glotzerlab/freud/blob/master/tests/test_locality_NeighborQuery.py

**Comment by blondegeek** [comment]
Closing this for now since this is mostly relevant to pre-processing.
