### ISSUE TITLE
voxel image❓ [QUESTION]

### ISSUE THREAD

**Issue by Chen-Cai-OSU** [e3nn/e3nn#183]
Hello,

I thought that TFN and 3d steerable CNN has been merged together into e3nn (might be wrong impression) but it seems that right now e3nn is mainly for point clouds. Should I still use 3d steerable CNN here https://github.com/mariogeiger/se3cnn if working with 3d images?

Also in se3cnn readme it is mentioned that ```For voxel I don't know which one is better```, does it imply that e3nn can also work for 3d image? Thank you for the clarification!

**Comment by blondegeek** [comment]
Hi @Chen-Cai-OSU,

You are correct that e3nn development has focused more on point clouds but still supports voxels. However, we have several default image / voxel network types [here](https://github.com/e3nn/e3nn/blob/447ccb253061a50b29f3a05c6eeffba34cca2c14/e3nn/networks/image.py) and tests showing how to initialize them [here](https://github.com/e3nn/e3nn/blob/447ccb253061a50b29f3a05c6eeffba34cca2c14/tests/networks_test.py#L77).

As far as which one to use, it depends -- se3cnn is more stable because it's no longer being developed, however e3nn some additional features such as equivariance to parity (inversion and therefore symmetries like mirrors).

We are also currently polishing a major code revision on the [main branch](https://github.com/e3nn/e3nn/tree/main). We have not decided to what degree we are going to focus on supporting voxels, simply because most of our primary users use point sets.

Hope that helps! Please feel free to re-open this issues if you have any further questions.

**Comment by Chen-Cai-OSU** [comment]
Thank you Tess!

**Comment by mariogeiger** [comment]
It is planned to support voxels better.
For that I plan to collaborate with users that needs it.
So far I have an example of voxel convolution in the main branch [here](https://github.com/e3nn/e3nn/blob/main/examples/voxel_convolution.py)
