### ISSUE TITLE
credits

### ISSUE THREAD

**Issue by mariogeiger** [e3nn/e3nn#196]
we could add a file like https://github.com/glotzerlab/freud/blob/master/doc/source/reference/credits.rst

**Comment by blondegeek** [comment]
That's a great idea -- I very much support this. Maybe we can talk about this in the monthly meeting.

**Comment by bdice** [comment]
I will warn that this kind of log takes some diligence to maintain, because contributors have to add themselves and track their own contributions in each PR.

Some alternatives:
- Pretty, automated-ish, feels human-friendly: https://allcontributors.org/
  - Example: https://github.com/nbQA-dev/nbQA/#-contributing
- Minimal-ish, lower-maintenance (no explicit steps required by the user on each PR): execute `git shortlog -sne > contributors.txt` at release time
  - Sample output: https://github.com/glotzerlab/freud/blob/master/contributors.txt
  - Also requires a `.mailmap` to ensure that git can track contributors by their canonical emails

**Comment by mariogeiger** [comment]
By what is it sorted?

**Comment by bdice** [comment]
The git shortlog is sorted by number of commits. The contributor list in freud’s docs is sorted “maintainers first, then by approximate date of first contribution.”

**Comment by mariogeiger** [comment]
Oh this is a problem because I like to "squash and merge" and then all contributors except me will have their number of commits divided by the average number of commits in one PR

**Comment by bdice** [comment]
Right. Squashing won’t work with the git shortlog method.
