### ISSUE TITLE
🌟 Get rid of temp file

### ISSUE THREAD

**Issue by mariogeiger** [e3nn/e3nn#249]
use `torch.fx` instead of saving code and loading files

**Comment by Linux-cpp-lisp** [comment]
See https://discuss.pytorch.org/t/subclass-of-fx-graphmodule-generating-its-own-code/115140/6 for some awkwardness if you need to access buffers / weights on the object itself. (In other words, if you want to generate `forward()` itself rather than a function called by `forward()`.)

 Generating the `_compiled_main_out` as a `torch.jit.script`ed `fx.GraphModule` should be no problem for `TensorProduct`.

**Comment by Linux-cpp-lisp** [comment]
The only issue for this will be the `Ellipsis` thing — either will need to eliminate `Ellipsis` from generated code or require PyTorch 1.8.1 which got the fix.

**Comment by Linux-cpp-lisp** [comment]
Should be resolved eventually by https://github.com/e3nn/e3nn/pull/262
