### ISSUE TITLE
❓ [QUESTION] Canonical way to transform from reducible to irreducible representations.

### ISSUE THREAD

**Issue by jhrmnn** [e3nn/e3nn#274]
First, let me say that I've just spent a few hours going through the documentation, and this is a really beautiful package and the documentation is superb.

Now the question: Let's say that I have a 2-rank tensor `P` that I know transforms as `2e * 2e` and that I want to use as an input to a e3nn-based architecture. So I first need to transform it to a direct sum of irreps. Would this code snippet be the canonical way how to do that with e3nn?

```python
P_irr = torch.einsum('ijk,jk->i', e3nn.o3.ReducedTensorProducts('ij', i='2e', j='2e').change_of_basis, P)
```

**Comment by mariogeiger** [comment]
Thanks for the feedback :-) 
I don't think there exist a canonical way to go. What you propose looks good :+1: .
Since you have no symmetry constraint you can as well get each individual irrep like that
```python
for l in [0, 1, 2, 3, 4]:
    P_irr = torch.einsum('ijk,jk->i', e3nn.o3.wigner_3j(l, 2, 2), P)
```
Be careful that the normalization might be different between the two proposed method (maybe `sqrt(2 * l + 1)` off, please check).

**Comment by jhrmnn** [comment]
Thanks!

**Comment by blondegeek** [comment]
Hi Jan,

Thanks for the question. I’ll also add that you will want to store which
change of basis matrix as it is non-unique.

Best!
Tess
