### ISSUE TITLE
🌟 Lazy initialization of Modules

### ISSUE THREAD

**Issue by blondegeek** [e3nn/e3nn#292]
When reloading a saved model, we currently have to recompute all relevant paths for e.g. `TensorProduct`. However, if we have a saved model, we already know these paths -- they are encoded in the `change_of_basis` matrix. It would be nice to be able to reload a module without having to re-initialize. @muhrin recommended that one approach would be lazy initialization -- we don't compute the paths until we need to or use the existing register_buffers

**Comment by mariogeiger** [comment]
You mean ReducedTensorProduct?

**Comment by blondegeek** [comment]
That's certainly one of the relevant modules, but I think this also applies
to TensorProduct. For example, in
https://github.com/e3nn/e3nn/blob/0.3.3/e3nn/o3/_tensor_product/_tensor_product.py#L260
-- what if I want to provide graph_out, graph_right, wigners and other
register buffers from a saved model rather than recompute?

**Comment by mariogeiger** [comment]
First I think `codegen_tensor_product` function executes super fast. It's not comparable with the computations done in `ReducedTensorProduct`.
Second, I think one can already save a module using `torch.jit.save`

**Comment by mariogeiger** [comment]
If you come up with a minimal example of code that you find slow such that I can identify which part is slow

**Comment by muhrin** [comment]
I haven't had a change to try it out yet but when discussing with Tess she mentioned that one of the problems when loading the model is that the class initialiser gets called (thereby incurring the path computation cost) when loading a module only for the paths to be subsequently overwritten.  If it's true that it's primarily the `ReduceTensorProduct` that is affected then we could focus on that.

One thing that occurred to me after the original discussion is that this approach would only work if 'lazy' was the _default_ option.  Otherwise, the constructor would just carry out the paths calculation even when loading (unless there is a way of determining if the class is being initialised as a result of a 'load' rather than just because the user is creating it).

**Comment by mariogeiger** [comment]
I need to see if there is a way to make it lazy while torch.script able at the same time

**Comment by muhrin** [comment]
Ah, I didn't realise that these two things could be incompatible.

**Comment by Linux-cpp-lisp** [comment]
@blondegeek not sure how you're saving/loading, but unless something is wrong Python pickling of models through `torch.save`/`torch.load` works just fine for us. Because of how I've architected `CodeGenMixin`, this doesn't recompile anything — the previously compiled TorchScript code is loaded direct from binary.

**Comment by blondegeek** [comment]
Hi Alby,

Do you save the model object or the state_dict? I typically save the
state_dict and that's I run into this issue -- one must first create a
model with a dict to fill in order load. I can try saving the object
directly instead.

Thanks!
Tess

**Comment by Linux-cpp-lisp** [comment]
Aha yeah we've been pickling the whole object — it's easier, since we don't need to be able to exactly re-do the building of a model for restarts, and that takes our own configuration options out of the backwards compatibility nightmare.

**Comment by mariogeiger** [comment]
@blondegeek  I think last release (0.4.2) fixes it. reopen if I'm wrong
