### ISSUE TITLE
Why now E(3) instead of SE(3)?

### ISSUE THREAD

**Issue by drewm1980** [e3nn/e3nn#3]
I would like to learn more about the transition from SE(3) to E(3). Do I understand correctly that the original intent was to be SE(3) equivariant, but the architecture turned out to also be E(3) equivariant? 

The ability to classify based on chirality was one of the advertised properties of the tensor field networks work; if that's still the case, then it seems that is the main differentiator between the two projects. i.e. if you want to train a classifier separating right and left handed screws, you should use tensorfieldnetworks, but if you don't want to be sensitive to that, you should use this e3nn repo.

https://github.com/tensorfieldnetworks/tensorfieldnetworks

Thanks for sharing and maintaining your work! I'm a big proponent of baking geometry into networks rather than defaulting to data augmentation.

**Comment by bkmi** [comment]
Hello there @drewm1980,

There are several differences between tensorfieldnetworks and e3nn. For one, e3nn includes a the code from the se3cnn paper which is very similar to TFNs but for volumetric data. You will find the routines for working with point data (like TFNs) in source code [e3nn/e3nn/point](https://github.com/e3nn/e3nn/tree/point/e3nn/point). Consider some of the examples to get started [e3nn/examples/point](https://github.com/e3nn/e3nn/tree/point/examples/point).

The reason we transitioned the repository into e3nn is because now the neural network can be equivariant to parity transformations if the user so chooses. [Consider the parity example here](https://github.com/e3nn/e3nn/blob/point/examples/point/tetris_parity.py). This is not a requirement at all, but since we have included the equivariant, it made sense to accurately represent that in the name of the repository.

**Comment by mariogeiger** [comment]
Hello @drewm1980,

With both a SE(3) and a E(3) equivariant network you are able to classify right and left handed screws.

Let me explain the difference between the two options with an example. Imagine you want to classify left-screws, right-screws and nails (nails are symmetric with respect to parity).
If you want to train a SE(3)-equivariant network to classify them you would have to show the 3 type of objects to the network. But if you opt for a E(3)-equivariant network you can train it with only left-screws and nails. No need to show him a right-screw since it's related to a left-screw by the parity operation. But still it will distinguish them. 
In this case you would typically encode the output with 2 scalars, an even and an odd. The sign of the even scalar will indicate if it's a screw or a nail and the sign of the odd scalar will indicate if it's a left or right screw (assuming it is a screw).

**Comment by drewm1980** [comment]
Thanks for the thorough response, @mariogeiger  and @bkmi !
