### ISSUE TITLE
document Clebsch-Gordon and spherical harmonic conventions.

### ISSUE THREAD

**Issue by blondegeek** [e3nn/e3nn#9]

**Comment by bkmi** [comment]
Aren't out spherical harmonics from scipy in the end? Therefore since the CGs are wigner d-matrices are calculated from the spherical harmonic conventions, they are determined by SciPy's conventions?

**Comment by mariogeiger** [comment]
the spherical harmonics and the wigner-d matrices are related by the following formula 
![CodeCogsEqn](https://user-images.githubusercontent.com/333780/77168984-098dbf80-6ab9-11ea-856d-77942dc2bd5f.gif)

There is a [slight adaptation](https://github.com/e3nn/e3nn/blob/master/e3nn/o3.py#L241) from the scipy convention: 
```python
Y = sh(J, M, pi - beta, alpha)
```
Note that this adaptation is only about the ZYZ parametrization.

Our wigned-d comes from lie_learn.

Then CG en wigner-d are related by the following formula
![CodeCogsEqn (1)](https://user-images.githubusercontent.com/333780/77169480-d3047480-6ab9-11ea-98c8-25e5fc9e9895.gif)

as you can see, this defines entirely CG up to a sign. Also note that since it has to be true for all rotations, it is not affected by the parametrization (we use ZYZ but it does not matter for Q).

The sign is [fixed](https://github.com/e3nn/e3nn/blob/master/e3nn/o3.py#L543-L544) as follow
```python
if next(x for x in Q.flatten() if x.abs() > 1e-10 * Q.abs().max()) < 0:
    Q.neg_()
```

**Comment by mariogeiger** [comment]
I renamed `clebsh_grodan` into `wigner_3j` in #69
